using System.Text;

namespace BFGetNames
{
	public static class JsonData
	{
		public static string GetJsonData()
		{
			StringBuilder sb = new StringBuilder();
			sb.AppendLine("[ ");
			sb.AppendLine("  {name: 'Afghanistan', code: 'AF'}, ");
			sb.AppendLine("  {name: 'Åland Islands', code: 'AX'}, ");
			sb.AppendLine("  {name: 'Albania', code: 'AL'}, ");
			sb.AppendLine("  {name: 'Algeria', code: 'DZ'}, ");
			sb.AppendLine("  {name: 'American Samoa', code: 'AS'}, ");
			sb.AppendLine("  {name: 'AndorrA', code: 'AD'}, ");
			sb.AppendLine("  {name: 'Angola', code: 'AO'}, ");
			sb.AppendLine("  {name: 'Anguilla', code: 'AI'}, ");
			sb.AppendLine("  {name: 'Antarctica', code: 'AQ'}, ");
			sb.AppendLine("  {name: 'Antigua and Barbuda', code: 'AG'}, ");
			sb.AppendLine("  {name: 'Argentina', code: 'AR'}, ");
			sb.AppendLine("  {name: 'Armenia', code: 'AM'}, ");
			sb.AppendLine("  {name: 'Aruba', code: 'AW'}, ");
			sb.AppendLine("  {name: 'Australia', code: 'AU'}, ");
			sb.AppendLine("  {name: 'Austria', code: 'AT'}, ");
			sb.AppendLine("  {name: 'Azerbaijan', code: 'AZ'}, ");
			sb.AppendLine("  {name: 'Bahamas', code: 'BS'}, ");
			sb.AppendLine("  {name: 'Bahrain', code: 'BH'}, ");
			sb.AppendLine("  {name: 'Bangladesh', code: 'BD'}, ");
			sb.AppendLine("  {name: 'Barbados', code: 'BB'}, ");
			sb.AppendLine("  {name: 'Belarus', code: 'BY'}, ");
			sb.AppendLine("  {name: 'Belgium', code: 'BE'}, ");
			sb.AppendLine("  {name: 'Belize', code: 'BZ'}, ");
			sb.AppendLine("  {name: 'Benin', code: 'BJ'}, ");
			sb.AppendLine("  {name: 'Bermuda', code: 'BM'}, ");
			sb.AppendLine("  {name: 'Bhutan', code: 'BT'}, ");
			sb.AppendLine("  {name: 'Bolivia', code: 'BO'}, ");
			sb.AppendLine("  {name: 'Bosnia and Herzegovina', code: 'BA'}, ");
			sb.AppendLine("  {name: 'Botswana', code: 'BW'}, ");
			sb.AppendLine("  {name: 'Bouvet Island', code: 'BV'}, ");
			sb.AppendLine("  {name: 'Brazil', code: 'BR'}, ");
			sb.AppendLine("  {name: 'British Indian Ocean Territory', code: 'IO'}, ");
			sb.AppendLine("  {name: 'Brunei Darussalam', code: 'BN'}, ");
			sb.AppendLine("  {name: 'Bulgaria', code: 'BG'}, ");
			sb.AppendLine("  {name: 'Burkina Faso', code: 'BF'}, ");
			sb.AppendLine("  {name: 'Burundi', code: 'BI'}, ");
			sb.AppendLine("  {name: 'Cambodia', code: 'KH'}, ");
			sb.AppendLine("  {name: 'Cameroon', code: 'CM'}, ");
			sb.AppendLine("  {name: 'Canada', code: 'CA'}, ");
			sb.AppendLine("  {name: 'Cape Verde', code: 'CV'}, ");
			sb.AppendLine("  {name: 'Cayman Islands', code: 'KY'}, ");
			sb.AppendLine("  {name: 'Central African Republic', code: 'CF'}, ");
			sb.AppendLine("  {name: 'Chad', code: 'TD'}, ");
			sb.AppendLine("  {name: 'Chile', code: 'CL'}, ");
			sb.AppendLine("  {name: 'China', code: 'CN'}, ");
			sb.AppendLine("  {name: 'Christmas Island', code: 'CX'}, ");
			sb.AppendLine("  {name: 'Cocos (Keeling) Islands', code: 'CC'}, ");
			sb.AppendLine("  {name: 'Colombia', code: 'CO'}, ");
			sb.AppendLine("  {name: 'Comoros', code: 'KM'}, ");
			sb.AppendLine("  {name: 'Congo', code: 'CG'}, ");
			sb.AppendLine("  {name: 'Congo, The Democratic Republic of the', code: 'CD'}, ");
			sb.AppendLine("  {name: 'Cook Islands', code: 'CK'}, ");
			sb.AppendLine("  {name: 'Costa Rica', code: 'CR'}, ");
			sb.AppendLine("  {name: 'Cote D\\'Ivoire', code: 'CI'}, ");
			sb.AppendLine("  {name: 'Croatia', code: 'HR'}, ");
			sb.AppendLine("  {name: 'Cuba', code: 'CU'}, ");
			sb.AppendLine("  {name: 'Cyprus', code: 'CY'}, ");
			sb.AppendLine("  {name: 'Czech Republic', code: 'CZ'}, ");
			sb.AppendLine("  {name: 'Denmark', code: 'DK'}, ");
			sb.AppendLine("  {name: 'Djibouti', code: 'DJ'}, ");
			sb.AppendLine("  {name: 'Dominica', code: 'DM'}, ");
			sb.AppendLine("  {name: 'Dominican Republic', code: 'DO'}, ");
			sb.AppendLine("  {name: 'Ecuador', code: 'EC'}, ");
			sb.AppendLine("  {name: 'Egypt', code: 'EG'}, ");
			sb.AppendLine("  {name: 'El Salvador', code: 'SV'}, ");
			sb.AppendLine("  {name: 'Equatorial Guinea', code: 'GQ'}, ");
			sb.AppendLine("  {name: 'Eritrea', code: 'ER'}, ");
			sb.AppendLine("  {name: 'Estonia', code: 'EE'}, ");
			sb.AppendLine("  {name: 'Ethiopia', code: 'ET'}, ");
			sb.AppendLine("  {name: 'Falkland Islands (Malvinas)', code: 'FK'}, ");
			sb.AppendLine("  {name: 'Faroe Islands', code: 'FO'}, ");
			sb.AppendLine("  {name: 'Fiji', code: 'FJ'}, ");
			sb.AppendLine("  {name: 'Finland', code: 'FI'}, ");
			sb.AppendLine("  {name: 'France', code: 'FR'}, ");
			sb.AppendLine("  {name: 'French Guiana', code: 'GF'}, ");
			sb.AppendLine("  {name: 'French Polynesia', code: 'PF'}, ");
			sb.AppendLine("  {name: 'French Southern Territories', code: 'TF'}, ");
			sb.AppendLine("  {name: 'Gabon', code: 'GA'}, ");
			sb.AppendLine("  {name: 'Gambia', code: 'GM'}, ");
			sb.AppendLine("  {name: 'Georgia', code: 'GE'}, ");
			sb.AppendLine("  {name: 'Germany', code: 'DE'}, ");
			sb.AppendLine("  {name: 'Ghana', code: 'GH'}, ");
			sb.AppendLine("  {name: 'Gibraltar', code: 'GI'}, ");
			sb.AppendLine("  {name: 'Greece', code: 'GR'}, ");
			sb.AppendLine("  {name: 'Greenland', code: 'GL'}, ");
			sb.AppendLine("  {name: 'Grenada', code: 'GD'}, ");
			sb.AppendLine("  {name: 'Guadeloupe', code: 'GP'}, ");
			sb.AppendLine("  {name: 'Guam', code: 'GU'}, ");
			sb.AppendLine("  {name: 'Guatemala', code: 'GT'}, ");
			sb.AppendLine("  {name: 'Guernsey', code: 'GG'}, ");
			sb.AppendLine("  {name: 'Guinea', code: 'GN'}, ");
			sb.AppendLine("  {name: 'Guinea-Bissau', code: 'GW'}, ");
			sb.AppendLine("  {name: 'Guyana', code: 'GY'}, ");
			sb.AppendLine("  {name: 'Haiti', code: 'HT'}, ");
			sb.AppendLine("  {name: 'Heard Island and Mcdonald Islands', code: 'HM'}, ");
			sb.AppendLine("  {name: 'Holy See (Vatican City State)', code: 'VA'}, ");
			sb.AppendLine("  {name: 'Honduras', code: 'HN'}, ");
			sb.AppendLine("  {name: 'Hong Kong', code: 'HK'}, ");
			sb.AppendLine("  {name: 'Hungary', code: 'HU'}, ");
			sb.AppendLine("  {name: 'Iceland', code: 'IS'}, ");
			sb.AppendLine("  {name: 'India', code: 'IN'}, ");
			sb.AppendLine("  {name: 'Indonesia', code: 'ID'}, ");
			sb.AppendLine("  {name: 'Iran, Islamic Republic Of', code: 'IR'}, ");
			sb.AppendLine("  {name: 'Iraq', code: 'IQ'}, ");
			sb.AppendLine("  {name: 'Ireland', code: 'IE'}, ");
			sb.AppendLine("  {name: 'Isle of Man', code: 'IM'}, ");
			sb.AppendLine("  {name: 'Israel', code: 'IL'}, ");
			sb.AppendLine("  {name: 'Italy', code: 'IT'}, ");
			sb.AppendLine("  {name: 'Jamaica', code: 'JM'}, ");
			sb.AppendLine("  {name: 'Japan', code: 'JP'}, ");
			sb.AppendLine("  {name: 'Jersey', code: 'JE'}, ");
			sb.AppendLine("  {name: 'Jordan', code: 'JO'}, ");
			sb.AppendLine("  {name: 'Kazakhstan', code: 'KZ'}, ");
			sb.AppendLine("  {name: 'Kenya', code: 'KE'}, ");
			sb.AppendLine("  {name: 'Kiribati', code: 'KI'}, ");
			sb.AppendLine("  {name: 'Korea, Democratic People\\'S Republic of', code: 'KP'}, ");
			sb.AppendLine("  {name: 'Korea, Republic of', code: 'KR'}, ");
			sb.AppendLine("  {name: 'Kuwait', code: 'KW'}, ");
			sb.AppendLine("  {name: 'Kyrgyzstan', code: 'KG'}, ");
			sb.AppendLine("  {name: 'Lao People\\'S Democratic Republic', code: 'LA'}, ");
			sb.AppendLine("  {name: 'Latvia', code: 'LV'}, ");
			sb.AppendLine("  {name: 'Lebanon', code: 'LB'}, ");
			sb.AppendLine("  {name: 'Lesotho', code: 'LS'}, ");
			sb.AppendLine("  {name: 'Liberia', code: 'LR'}, ");
			sb.AppendLine("  {name: 'Libyan Arab Jamahiriya', code: 'LY'}, ");
			sb.AppendLine("  {name: 'Liechtenstein', code: 'LI'}, ");
			sb.AppendLine("  {name: 'Lithuania', code: 'LT'}, ");
			sb.AppendLine("  {name: 'Luxembourg', code: 'LU'}, ");
			sb.AppendLine("  {name: 'Macao', code: 'MO'}, ");
			sb.AppendLine("  {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'}, ");
			sb.AppendLine("  {name: 'Madagascar', code: 'MG'}, ");
			sb.AppendLine("  {name: 'Malawi', code: 'MW'}, ");
			sb.AppendLine("  {name: 'Malaysia', code: 'MY'}, ");
			sb.AppendLine("  {name: 'Maldives', code: 'MV'}, ");
			sb.AppendLine("  {name: 'Mali', code: 'ML'}, ");
			sb.AppendLine("  {name: 'Malta', code: 'MT'}, ");
			sb.AppendLine("  {name: 'Marshall Islands', code: 'MH'}, ");
			sb.AppendLine("  {name: 'Martinique', code: 'MQ'}, ");
			sb.AppendLine("  {name: 'Mauritania', code: 'MR'}, ");
			sb.AppendLine("  {name: 'Mauritius', code: 'MU'}, ");
			sb.AppendLine("  {name: 'Mayotte', code: 'YT'}, ");
			sb.AppendLine("  {name: 'Mexico', code: 'MX'}, ");
			sb.AppendLine("  {name: 'Micronesia, Federated States of', code: 'FM'}, ");
			sb.AppendLine("  {name: 'Moldova, Republic of', code: 'MD'}, ");
			sb.AppendLine("  {name: 'Monaco', code: 'MC'}, ");
			sb.AppendLine("  {name: 'Mongolia', code: 'MN'}, ");
			sb.AppendLine("  {name: 'Montserrat', code: 'MS'}, ");
			sb.AppendLine("  {name: 'Morocco', code: 'MA'}, ");
			sb.AppendLine("  {name: 'Mozambique', code: 'MZ'}, ");
			sb.AppendLine("  {name: 'Myanmar', code: 'MM'}, ");
			sb.AppendLine("  {name: 'Namibia', code: 'NA'}, ");
			sb.AppendLine("  {name: 'Nauru', code: 'NR'}, ");
			sb.AppendLine("  {name: 'Nepal', code: 'NP'}, ");
			sb.AppendLine("  {name: 'Netherlands', code: 'NL'}, ");
			sb.AppendLine("  {name: 'Netherlands Antilles', code: 'AN'}, ");
			sb.AppendLine("  {name: 'New Caledonia', code: 'NC'}, ");
			sb.AppendLine("  {name: 'New Zealand', code: 'NZ'}, ");
			sb.AppendLine("  {name: 'Nicaragua', code: 'NI'}, ");
			sb.AppendLine("  {name: 'Niger', code: 'NE'}, ");
			sb.AppendLine("  {name: 'Nigeria', code: 'NG'}, ");
			sb.AppendLine("  {name: 'Niue', code: 'NU'}, ");
			sb.AppendLine("  {name: 'Norfolk Island', code: 'NF'}, ");
			sb.AppendLine("  {name: 'Northern Mariana Islands', code: 'MP'}, ");
			sb.AppendLine("  {name: 'Norway', code: 'NO'}, ");
			sb.AppendLine("  {name: 'Oman', code: 'OM'}, ");
			sb.AppendLine("  {name: 'Pakistan', code: 'PK'}, ");
			sb.AppendLine("  {name: 'Palau', code: 'PW'}, ");
			sb.AppendLine("  {name: 'Palestinian Territory, Occupied', code: 'PS'}, ");
			sb.AppendLine("  {name: 'Panama', code: 'PA'}, ");
			sb.AppendLine("  {name: 'Papua New Guinea', code: 'PG'}, ");
			sb.AppendLine("  {name: 'Paraguay', code: 'PY'}, ");
			sb.AppendLine("  {name: 'Peru', code: 'PE'}, ");
			sb.AppendLine("  {name: 'Philippines', code: 'PH'}, ");
			sb.AppendLine("  {name: 'Pitcairn', code: 'PN'}, ");
			sb.AppendLine("  {name: 'Poland', code: 'PL'}, ");
			sb.AppendLine("  {name: 'Portugal', code: 'PT'}, ");
			sb.AppendLine("  {name: 'Puerto Rico', code: 'PR'}, ");
			sb.AppendLine("  {name: 'Qatar', code: 'QA'}, ");
			sb.AppendLine("  {name: 'Reunion', code: 'RE'}, ");
			sb.AppendLine("  {name: 'Romania', code: 'RO'}, ");
			sb.AppendLine("  {name: 'Russian Federation', code: 'RU'}, ");
			sb.AppendLine("  {name: 'RWANDA', code: 'RW'}, ");
			sb.AppendLine("  {name: 'Saint Helena', code: 'SH'}, ");
			sb.AppendLine("  {name: 'Saint Kitts and Nevis', code: 'KN'}, ");
			sb.AppendLine("  {name: 'Saint Lucia', code: 'LC'}, ");
			sb.AppendLine("  {name: 'Saint Pierre and Miquelon', code: 'PM'}, ");
			sb.AppendLine("  {name: 'Saint Vincent and the Grenadines', code: 'VC'}, ");
			sb.AppendLine("  {name: 'Samoa', code: 'WS'}, ");
			sb.AppendLine("  {name: 'San Marino', code: 'SM'}, ");
			sb.AppendLine("  {name: 'Sao Tome and Principe', code: 'ST'}, ");
			sb.AppendLine("  {name: 'Saudi Arabia', code: 'SA'}, ");
			sb.AppendLine("  {name: 'Senegal', code: 'SN'}, ");
			sb.AppendLine("  {name: 'Serbia and Montenegro', code: 'CS'}, ");
			sb.AppendLine("  {name: 'Seychelles', code: 'SC'}, ");
			sb.AppendLine("  {name: 'Sierra Leone', code: 'SL'}, ");
			sb.AppendLine("  {name: 'Singapore', code: 'SG'}, ");
			sb.AppendLine("  {name: 'Slovakia', code: 'SK'}, ");
			sb.AppendLine("  {name: 'Slovenia', code: 'SI'}, ");
			sb.AppendLine("  {name: 'Solomon Islands', code: 'SB'}, ");
			sb.AppendLine("  {name: 'Somalia', code: 'SO'}, ");
			sb.AppendLine("  {name: 'South Africa', code: 'ZA'}, ");
			sb.AppendLine("  {name: 'South Georgia and the South Sandwich Islands', code: 'GS'}, ");
			sb.AppendLine("  {name: 'Spain', code: 'ES'}, ");
			sb.AppendLine("  {name: 'Sri Lanka', code: 'LK'}, ");
			sb.AppendLine("  {name: 'Sudan', code: 'SD'}, ");
			sb.AppendLine("  {name: 'Suriname', code: 'SR'}, ");
			sb.AppendLine("  {name: 'Svalbard and Jan Mayen', code: 'SJ'}, ");
			sb.AppendLine("  {name: 'Swaziland', code: 'SZ'}, ");
			sb.AppendLine("  {name: 'Sweden', code: 'SE'}, ");
			sb.AppendLine("  {name: 'Switzerland', code: 'CH'}, ");
			sb.AppendLine("  {name: 'Syrian Arab Republic', code: 'SY'}, ");
			sb.AppendLine("  {name: 'Taiwan, Province of China', code: 'TW'}, ");
			sb.AppendLine("  {name: 'Tajikistan', code: 'TJ'}, ");
			sb.AppendLine("  {name: 'Tanzania, United Republic of', code: 'TZ'}, ");
			sb.AppendLine("  {name: 'Thailand', code: 'TH'}, ");
			sb.AppendLine("  {name: 'Timor-Leste', code: 'TL'}, ");
			sb.AppendLine("  {name: 'Togo', code: 'TG'}, ");
			sb.AppendLine("  {name: 'Tokelau', code: 'TK'}, ");
			sb.AppendLine("  {name: 'Tonga', code: 'TO'}, ");
			sb.AppendLine("  {name: 'Trinidad and Tobago', code: 'TT'}, ");
			sb.AppendLine("  {name: 'Tunisia', code: 'TN'}, ");
			sb.AppendLine("  {name: 'Turkey', code: 'TR'}, ");
			sb.AppendLine("  {name: 'Turkmenistan', code: 'TM'}, ");
			sb.AppendLine("  {name: 'Turks and Caicos Islands', code: 'TC'}, ");
			sb.AppendLine("  {name: 'Tuvalu', code: 'TV'}, ");
			sb.AppendLine("  {name: 'Uganda', code: 'UG'}, ");
			sb.AppendLine("  {name: 'Ukraine', code: 'UA'}, ");
			sb.AppendLine("  {name: 'United Arab Emirates', code: 'AE'}, ");
			sb.AppendLine("  {name: 'United Kingdom', code: 'GB'}, ");
			sb.AppendLine("  {name: 'United States', code: 'US'}, ");
			sb.AppendLine("  {name: 'United States Minor Outlying Islands', code: 'UM'}, ");
			sb.AppendLine("  {name: 'Uruguay', code: 'UY'}, ");
			sb.AppendLine("  {name: 'Uzbekistan', code: 'UZ'}, ");
			sb.AppendLine("  {name: 'Vanuatu', code: 'VU'}, ");
			sb.AppendLine("  {name: 'Venezuela', code: 'VE'}, ");
			sb.AppendLine("  {name: 'Viet Nam', code: 'VN'}, ");
			sb.AppendLine("  {name: 'Virgin Islands, British', code: 'VG'}, ");
			sb.AppendLine("  {name: 'Virgin Islands, U.S.', code: 'VI'}, ");
			sb.AppendLine("  {name: 'Wallis and Futuna', code: 'WF'}, ");
			sb.AppendLine("  {name: 'Western Sahara', code: 'EH'}, ");
			sb.AppendLine("  {name: 'Yemen', code: 'YE'}, ");
			sb.AppendLine("  {name: 'Zambia', code: 'ZM'}, ");
			sb.AppendLine("  {name: 'Zimbabwe', code: 'ZW'} ");
			sb.AppendLine("]");
			return sb.ToString();
		}
	}
}